# numpy


- 행렬 / 선형대수 / 통계 패키지

- 머신러닝의 이론적 백그라운드는 선형대수와 통계로 이루어져 있다

- 사이킷런 같은 머신러닝 패키지가 넘파이 기반으로 되어 있다


    * 머신러닝 알고리즘이나 사이파이와 같은 과학, 통계 지원용 패키지를 직접 만드는 개발이 아니라면
    넘파이를 상세하기 알 필요는 없다지만, 넘파이를 이해하는 것이 파이썬 기반의 데이타분석과 머신러닝에 중요하다
    
    * 넘파이가 데이타 핸들링에 효율적으로 쉽고 편하고 할 수 없다.
      그러나 데이타 핸들링에 주로 사용하는 판다스도 많은 부분이 넘파이를 기반으로 만들어져 있다.
    
     -> 이번 수업을 가볍게 구경하듯이 하다가 추후에 이 부분이 나오면 다시 집중해서 보는 방식을 해도 된다

    
    * ndarray 
        - 넘파이 기반 데이타 타입
        - np.array()       

In [1]:
import numpy as np

list_1 = [1, 2, 3]  # 파이썬의 리스트
list_2 = [9, 8, 7]
arr = np.array([list_1, list_2]) # 넘파이의 ndarray
print(arr)
print(type(arr))  # 자료형 확인
print(arr.shape)  # 형태 확인

# 넘파이 기반의 데이타 타입이 ndarray 이다

[[1 2 3]
 [9 8 7]]
<class 'numpy.ndarray'>
(2, 3)


In [2]:
## 두번째 행 두번째 열의 요소를 100으로 지정
arr[1][1]=100
arr

array([[  1,   2,   3],
       [  9, 100,   7]])

In [3]:
# 도움말보기 ( 쉘창 실행 : shift + enter )
# arr에 커서는 놓고 shift + tab
?arr

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3]])

## 자료형과 형태를 확인
print(type(arr1))
print(arr1.shape)

print(type(arr2))
print(arr2.shape)

# [결과]
# (3,) ->  1차원 튜플로 3개의 요소를 가진  (** 헷갈린다)
# (1, 3) -> 1행 3열의 2차원 형태

# 차원수 확인
print(arr1.ndim,'차원')
print(arr2.ndim,'차원')

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(1, 3)
1 차원
2 차원


### 자료형

[ 참고 ] 

    - 넘파이의 배열 안에는 동일한 타입의 데이터만 저장
    - 이 점 때문에 넘파이가 계산을 쉽고 빠르게 처리한다
    - 동일한 자료형으로만 데이터를 저장하면 필요한 저장공간이 일정하기에,
      원하는 위치에 바로 접근하여 데이타를 읽을 수 있기 때문이다.

In [5]:
# 자료형보기
print(type(arr))

# nparray의 요소의 자료형 보기
print(arr.dtype)

<class 'numpy.ndarray'>
int32


In [6]:
# 타입 변경
# 머신러닝에서 데이타를 정규분포나 0~1 사이 값을 맞추기 위해 많이 사용 
arr_2 = arr.astype(np.float64)
arr_2

array([[  1.,   2.,   3.],
       [  9., 100.,   7.]])

In [7]:
# np.array() 이용 : float 배열을  int32형으로 변경
in_sample = [2.1, 3.2, 4.3]
arr_sample = np.array(in_sample, dtype='int32')
arr_sample

array([2, 3, 4])

In [8]:
# 다른 자료형의 요소들을 가진 리스트를 ndarray로 배열로 변환시 자료형 확인

list1 = [1, 2, 3.6 ]   # 정수, 정수, 실수
arr1 = np.array(list1)
print(arr1)
print(arr1.dtype)      # nparray의 요소의 자료형 보기

list2 = [1, 2.9, 'PYTHON' ]   # 정수, 정수, 문자열
arr2 = np.array(list2)
print(arr2)
print(arr2.dtype)      # [결과] <U32   : Unicode 문자열 

[1.  2.  3.6]
float64
['1' '2.9' 'PYTHON']
<U32


### nparray를 편리하게 생성

* arange() : 범위를 이용한 배열 만들기
            - range() 비교
            - np.array(range(5))
* zeros() : 0으로 채우는 배열 만들기
* ones() : 1로 채우는 배열 만들기

In [9]:
import numpy as np
a = np.arange(10)   # 범위를 이용한 배열 만들기
a

b= np.arange(1,11)
b

c = np.arange(1, 11, 3)
c

array([ 1,  4,  7, 10])

In [10]:
a2 = np.zeros((5,5))  
a2                  # 기본 데이타타입이 float

a3 = np.zeros((5,5), dtype='int32')
a3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
## 1로 채워진 3행 4열의 정수 배열 생성
a4 = np.ones((3,4), dtype='int32')
a4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### ndarray의 차원과 크기를 변경 : reshape()

+ flatten() : 평탄화 함수


In [14]:
# -1 적용

arr = np.arange(20)
print(arr)
print(arr2.shape)

# 차원과 크기 변경
arr1 = arr.reshape(4,5)
print(arr1)
print(arr1.shape)

arr2 = arr.reshape(5, -1)
print(arr2)

arr3 = arr.reshape(-1, 5)
print(arr3)

arr4 = arr.reshape(-1, 4)
print(arr4)

# arr5 = arr.reshape(-1, 3) # 에러 발생 : 행과 열수 안 맞음
# print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### 인덱싱: 특정 데이타 추출

In [18]:
# 2차원 배열에서  슬라이싱은 그림을 보여주면 하자
"""
    1 2 3
    4 5 6
    7 8 9
"""

arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)
    
## 행렬에서 1, 2, 4, 5 추출 ( 이것만 해주자)
print(ndarr[:2, :2])
# ndarr[0:2][0:2] 은 이미 ndarr[0:2] 행을 추출하고 다시 [0:2]행을 또 추출하는 경우이다. 즉 두번째가 열을 추출하지 않느다

## 행렬에서 4, 5, 6, 7, 8, 9 추출
print(ndarr[1:, :])

## 행렬에서 2, 3, 5, 6 추출
print(ndarr[:2, 1:])

## 행렬에서 1, 4 추출
print(ndarr[:2, 0])

## 행렬에서 전체 요소 추출
print(ndarr[:,:])
print(ndarr[::])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# 2차원 ndarray에서 뒤의 오는 인덱스가 없으면 1차원으로 반환
# 3차원 ndarray에서 뒤의 오는 인덱스가 없으면 2차원으로 반환

# print(ndarr[1][1])
# print(ndarr[1])       # 1차원 ndarray 반환

In [20]:
# 슬라이싱[:]과 인덱스선택을 결합

# 2차원 배열에서  슬라이싱은 그림을 보여주면 하자
"""
    1 2 3
    4 5 6
    7 8 9
"""
import numpy as np
arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)

## 행렬에서 1, 2, 4, 5 추출 ( 이것만 해주자)
print(ndarr[[0,1], :2])
print(ndarr[:2, :2])
print(ndarr[[0,1],[0,1]]) # 결과 다름 0 , 5

## 행렬에서 4, 5, 6, 7, 8, 9 추출
print(ndarr[[1,2]])

## 행렬에서 2, 3, 5, 6 추출
print(ndarr[[0,1],1:])

## 행렬에서 1, 4 추출
print(ndarr[[0,1], 0])

## 행렬에서 3, 6 추출
print(ndarr[[0,1], 2])

# 지금은 너무 간단하다고 여기지만 추후에 데이타에서 많이 헷갈려서 여기서 시간 소요를 많이 한다

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[1 5]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
[3 6]


In [21]:
#------------------------------------------ (3) 블린인덱싱
# 조건 필터링과 검색을 같이 하기에 자주 사용

arr = np.arange(1, 10)
ndarr = arr.reshape(3,3)
print(ndarr)

# 5보다 큰 요소들 추출
print(ndarr>5)
print(ndarr[ndarr>5])

# 8값 요소를 찾아서 88로 변경
print(ndarr== 8)
ndarr[ndarr==8]=88
print(ndarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[[False False False]
 [False False False]
 [False  True False]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7 88  9]]
