### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. np.array.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. np.array.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [1]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [2]:
# 넘파이 sort
sorted1 = np.sort(origin)
print('원본:', origin)
print('정렬된 후:', sorted1)

원본: [3 1 9 7]
정렬된 후: [1 3 7 9]


In [3]:
# 행렬의 sort
sorted2 = origin.sort()
print('원본:', origin)
print('정렬된 후:', sorted2)

원본: [1 3 7 9]
정렬된 후: None


### 내림차순 정렬 [::-1]

In [4]:
# 위의 코드들을 복사하여 사용하자

origin = np.array([8,3,9,2])
sorted1 = np.sort(origin)[::-1]
print('원본:', origin)
print('정렬된 후:', sorted1)

원본: [8 3 9 2]
정렬된 후: [9 8 3 2]


In [5]:
sorted2 = origin.sort()[::-1]    # 에러 발생을 확인
print('원본:', origin)
print('정렬된 후:', sorted2)

TypeError: 'NoneType' object is not subscriptable

### 2차원 이상의 행렬에서   np.sort()  이해하기

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [6]:
import numpy as np
arr = np.array([[9, 6, 3],[5, 11, 2]])
print(arr)


row_sort = np.sort(arr, axis=0)
print(row_sort)


row_sort = np.sort(arr, axis=1)
print(row_sort)


[[ 9  6  3]
 [ 5 11  2]]
[[ 5  6  2]
 [ 9 11  3]]
[[ 3  6  9]
 [ 2  5 11]]


In [7]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [8]:
arr = np.array([3, 8, 2, 5])
sorted = np.sort(arr)
print(sorted)

idx = np.argsort(arr)
print('정렬시 원본 행렬의 인덱스 :', idx)  # 기본이 내림차순인거야?


[2 3 5 8]
정렬시 원본 행렬의 인덱스 : [2 0 3 1]
정렬시 원본 행렬의 인덱스 : [1 3 0 2]


In [9]:
# 성적과 학생명이 있는 경우 정렬 후 매칭하기 위해 
scores = np.array([66, 99, 55, 88, 77])
names = np.array(['홍길동','박길동','김길동','맹길동','이길동'])

## 점수를 내림차순으로 정렬하고 이름을 점수에 내림차순에 맞게 출력
idx=np.argsort(scores)[::-1]
print(idx)

for i in idx:
    print(scores[i],':', names[i])

[1 3 4 0 2]
99 : 박길동
88 : 맹길동
77 : 이길동
66 : 홍길동
55 : 김길동
