**역행렬**

**원래 행렬과 역핵렬을 행렬의 곱으로 하면 단위행렬**

In [2]:
import numpy as np

x = np.array([[1,2],[3,4]])

# 역행렬
y = np.linalg.inv(x)
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
# 행렬의 곱

np.dot(x,y)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [5]:
np.matmul(x,y)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [8]:
x = np.array([[1,2,3],[3,4,5],[4,5,6]])

# 역행렬
y = np.linalg.inv(x)
y

# 행렬의곱
print(np.dot(x,y))
print(np.matmul(x,y))

[[ 2.  0.  4.]
 [ 6.  0. 12.]
 [ 4.  0.  8.]]
[[ 2.  0.  4.]
 [ 6.  0. 12.]
 [ 4.  0.  8.]]


In [9]:
x = np.array([[1,2,3,4],[3,4,5,6],[4,5,6,6],[5,6,7,8]])

# 역행렬
y = np.linalg.inv(x)
y

# 행렬의곱
print(np.dot(x,y))
print(np.matmul(x,y))

[[ 5.00000000e-01  0.00000000e+00  8.88178420e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  0.00000000e+00]
 [ 0.00000000e+00 -4.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]]
[[ 5.00000000e-01  0.00000000e+00  8.88178420e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  0.00000000e+00]
 [ 0.00000000e+00 -4.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00]]


In [12]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])

print(a)
print('-'*50)
print(c)
print('='*50)

print(np.dot(a, c).shape) #  (9, 5, 7, 9, 5, 3)
print(np.matmul(a, c).shape) #  (9, 5, 7, 3)
# n is 7, k is 4, m is 3

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]
